user: "haider_1"
password: "haider"


chunk_size: 5 # Smaller the Chunk size, less the speed
typing_wait_seconds: 0.2 # Slows down typing speed (combines with Chunk Size for controlling speed)
max_race: 5 # Total number of races
disturb_accuracy: 4 # Scale on how much to disturb accuracy